### ISSUE TITLE
default environment is not loaded with ApplicationContextConfigurer

### ISSUE THREAD

**Issue by harikrishna553** [micronaut-projects/micronaut-aot#149] opened 2022-11-04 05:56 UTC
### Expected Behavior

Default environment should be set by implementing ApplicationContextConfigurer interface

### Actual Behaviour

Properties from default environment are not loaded, when I do not set the environment explicitly

### Steps To Reproduce

I am going through the 'Default Environment' section of [user guide](https://docs.micronaut.io/latest/guide). Using below code to configure the default environment.

`public class App {

	@ContextConfigurer
	public static class DefaultEnvironmentConfigurer implements ApplicationContextConfigurer {
		@Override
		public void configure(@NonNull ApplicationContextBuilder builder) {
			builder.defaultEnvironments("dev", "qa");
		}
	}

	public static void main(String[] args) {

		try (ApplicationContext applicationContext = Micronaut.run(App.class, args)) {

			Environment environment = applicationContext.getEnvironment();

			String a1 = environment.getProperty("a1", String.class, "a1");
			String a2 = environment.getProperty("a2", String.class, "a2");

			System.out.println("a1 : " + a1);
			System.out.println("a2 : " + a2);
		}

	}
}`

Default environment properties are not laoded, when I do not configure the environment explicitly.

### Environment Information

- Mac os
- JDK 15
- Micronaut 3.7.3

### Example Application

https://github.com/harikrishna553/java-libs/tree/master/micronaut/app-configuration/micronaut-specify-envt-programatically

### Version

3.7.3

**Comment by altro3** [comment] 2023-03-04 20:12
@harikrishna553 All works fine, but  this does not concern aot at all. Your example does not use aot.

Your example doesn't work because you made a mistake. You didn't include the micronaut-inject annotation processor, so your class annotated with `@DefaultEnvironmentConfigurer` is simply ignored. Here is an example of correct pom file using micronaut plugin:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.sample.app</groupId>
    <artifactId>micronaut-specify-envt-programatically</artifactId>
    <version>1</version>

    <parent>
        <groupId>io.micronaut</groupId>
        <artifactId>micronaut-parent</artifactId>
        <version>3.8.6</version>
    </parent>

    <properties>
        <packaging>jar</packaging>
        <jdk.version>1.8</jdk.version>
        <!-- If you are building with JDK 9 or higher, you can uncomment the lines below to set the release version -->
        <!-- <release.version>8</release.version> -->
        <micronaut.version>3.8.6</micronaut.version>
        <micronaut.runtime>netty</micronaut.runtime>
        <exec.mainClass>com.example.Application</exec.mainClass>
        <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.source>17</maven.compiler.source>
    </properties>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
    </repositories>

    <dependencies>

        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-inject-java</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-validation</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-http-server-netty</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.micronaut.build</groupId>
                <artifactId>micronaut-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.micronaut</groupId>
                            <artifactId>micronaut-validation</artifactId>
                            <version>${micronaut.version}</version>
                        </path>
                        <path>
                            <groupId>io.micronaut</groupId>
                            <artifactId>micronaut-inject-java</artifactId>
                            <version>${micronaut.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

        </plugins>
    </build>
</project>

```

**Comment by altro3** [comment] 2023-03-04 20:14
@melix Could you close this issue? This is not a bug and has nothing to do with aot

**Closed** 2023-03-06 07:30 UTC
